name: Github Issues Labels Replacer

# Set jobs to be configured and executed by schedule.
on:
  push:
    branches:
      - 'main'

  schedule:
    - cron: '0 8 * * 1-5' # Actions will be executed at 8am for every weekday.

env:
  GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: "Replace labels for Observability,Component:Search"
        env:
          REPLACEMENT_LABELS: "squad:observability,component:search"
          SQUAD_LABEL: "squad:observability-usa"
          TARGET_LABELS: "squad:observability-usa"
        run: |
          gem install octokit
          gem install colorize
          ruby scripts/github/issues/label-replacer.rb
